### ISSUE TITLE
List Trinity Matrix Management on the Try Matrix Now page

### ISSUE THREAD

**Issue by MilkManzJourDaddy** [aminhusni/Trinity_Matrix_Management_GUI#1]
For more exposure you will want a listing, probably on https://matrix.org/docs/projects/try-matrix-now.html#other •Near the top of that Try Matrix Now page, it instructs to file a PR in https://github.com/matrix-org/matrix-doc •to get your project listed.  Good luck.

**Comment by aminhusni** [comment]
Thank you for the information :)

**Comment by MilkManzJourDaddy** [comment]
Thanks for this project.  We hope it continues to thrive.
