### ISSUE TITLE
Add Install instructions and usage examples to README

### ISSUE THREAD

**Issue by rubo77** [aminhusni/Trinity_Matrix_Management_GUI#2]
Please add instructions how to setup this tool, including dependencies, how to upgrade,  and so on.

example: https://github.com/ffnord/mesh-announce/blob/master/README.md

**Comment by CarrollLiddel** [comment]
Hi, I would also love that.

**Comment by rubo77** [comment]
Could you please at least give a hint here?

**Comment by aminhusni** [comment]
Hi, 

If you want to give the program a try, please get the latest installation binary from the releases section. 

https://github.com/aminhusni/Trinity_Matrix_Management_GUI/releases

Extract Trinity.zip and double click the installer.

**Comment by rubo77** [comment]
Does this work on Linux?

Can you please also add instruction how to compile on Linux?

**Comment by aminhusni** [comment]
I think it can run in Linux if you use Mono. However, I am not sure if Linux has WPF support. 
Maybe you can try it on Wine
