### ISSUE TITLE
Login not possible

### ISSUE THREAD

**Issue by rubo77** [aminhusni/Trinity_Matrix_Management_GUI#5]
On Windows 10, I downloaded release 2.1. Now, I try to login with my credentials of my admin user on my matrix server (that works fine on other, commandline- tools).

If I enter the wrong credentials I get the error message "Authorization error". When I enter the correct password, the Login button gets greyed out and it sais "Logging in, please wait" for about 3.5 seconds, then the Login button is free again to click. 

Nothing happens!

How can I help to debug this?

**Comment by aminhusni** [comment]
Tested on version 2.1
Windows 10

Could not replicate the problem. 
For debugging, perhaps it is a good idea to install Visual Studio first and try running the program from source code. 

Appreciate your support :)

**Comment by rubo77** [comment]
Could you add a warning, on the second login failure with correct password?

**Comment by aminhusni** [comment]
I don't get what you mean by "second login failure with correct password". 

I tried entering the wrong password on 1st attempt and entering the correct password on 2nd attempt. My login was successful.

**Comment by rubo77** [comment]
I thought about the point where the program checks the log in. There must be a point in the execution between logging in and showing the rest of the program , if that fails there should be another warning.

At the moment it only shows the login screen again which doesn't help much

**Comment by aminhusni** [comment]
If you login with wrong details, you will get a warning on version 2.1

![2019-02-10 03_58_58-](https://user-images.githubusercontent.com/8511047/52525700-4dc06500-2ce8-11e9-9b55-ef1859a800a6.png)

Could not reproduce the error described in this Issue

**Comment by rubo77** [comment]
Which is the code part of the login? Maybe I can find something out there

**Comment by aminhusni** [comment]
https://github.com/aminhusni/Trinity_Matrix_Management_GUI/blob/1257475bca123f739ff5bb5963e65653ef75d20b/MainWindow.xaml.cs#L20

**Comment by rubo77** [comment]
maybe you can change line 64 so the exception is shown instead of just logged:

https://github.com/aminhusni/Trinity_Matrix_Management_GUI/blob/1257475bca123f739ff5bb5963e65653ef75d20b/MainWindow.xaml.cs#L46

statustext.Content = "Error: " + ex;

Or add a debug log somewhere in the installation, so you find the error there.

**Comment by rubo77** [comment]
How do I start the app in visual studio? I have 

- installed "Visual Studio Code"
- downoaded and unzipped this repo
- chose "open Folder" in vusual studio code

now I am lost with my first encounter of visual basic ;)

which file is the main program, and how do I run it in visual studio code?

I tried  open the `Trinity.csproj` file and press "Start without Debugging" but then I only get a selection "Select Environmeht" where i can oly select node.js.

Maybe I have to Install the  "C# dependency" in the upcoming dialogue in the right bottom corner? and .NET CLI tools ?

I'll try installing from here now: https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install

**Comment by rubo77** [comment]
Maybe this is a problem? I see in the output:

```

[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for framework ".NETFramework,Version=v4.6.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\tmp\Trinity\src\Trinity.csproj'.
```

**Comment by aminhusni** [comment]
You need Microsoft Visual Studio to develop for .NET applications. 
Visual Studio Code is just a text editor. 

Try getting the community edition from here

https://visualstudio.microsoft.com/vs/
